# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BPMOptionsPage(object):
    def setupUi(self, BPMOptionsPage):
        BPMOptionsPage.setObjectName("BPMOptionsPage")
        BPMOptionsPage.resize(495, 273)
        self.gridLayout_2 = QtWidgets.QGridLayout(BPMOptionsPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bpm_options = QtWidgets.QGroupBox(BPMOptionsPage)
        self.bpm_options.setObjectName("bpm_options")
        self.slider_default = QtWidgets.QLabel(self.bpm_options)
        self.slider_default.setGeometry(QtCore.QRect(8, 80, 43, 19))
        self.slider_default.setToolTip("")
        self.slider_default.setObjectName("slider_default")
        self.slider_parameter = QtWidgets.QSlider(self.bpm_options)
        self.slider_parameter.setGeometry(QtCore.QRect(20, 51, 391, 23))
        self.slider_parameter.setMinimum(1)
        self.slider_parameter.setMaximum(3)
        self.slider_parameter.setOrientation(QtCore.Qt.Horizontal)
        self.slider_parameter.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_parameter.setTickInterval(1)
        self.slider_parameter.setObjectName("slider_parameter")
        self.slider_super_fast = QtWidgets.QLabel(self.bpm_options)
        self.slider_super_fast.setGeometry(QtCore.QRect(370, 80, 61, 19))
        self.slider_super_fast.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.slider_super_fast.setObjectName("slider_super_fast")
        self.line = QtWidgets.QFrame(self.bpm_options)
        self.line.setGeometry(QtCore.QRect(10, 120, 471, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.bpm_options)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(6, 140, 471, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.horizontalLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.samplerate_value = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.samplerate_value.setText("")
        self.samplerate_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.samplerate_value.setObjectName("samplerate_value")
        self.gridLayout.addWidget(self.samplerate_value, 2, 1, 1, 1)
        self.hop_s_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.hop_s_label.setObjectName("hop_s_label")
        self.gridLayout.addWidget(self.hop_s_label, 1, 0, 1, 1)
        self.win_s_value = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.win_s_value.setText("")
        self.win_s_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.win_s_value.setObjectName("win_s_value")
        self.gridLayout.addWidget(self.win_s_value, 0, 1, 1, 1)
        self.hop_s_value = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.hop_s_value.setText("")
        self.hop_s_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hop_s_value.setObjectName("hop_s_value")
        self.gridLayout.addWidget(self.hop_s_value, 1, 1, 1, 1)
        self.win_s_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.win_s_label.setObjectName("win_s_label")
        self.gridLayout.addWidget(self.win_s_label, 0, 0, 1, 1)
        self.samplerate_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.samplerate_label.setObjectName("samplerate_label")
        self.gridLayout.addWidget(self.samplerate_label, 2, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout_2.addWidget(self.bpm_options, 0, 0, 1, 1)

        self.retranslateUi(BPMOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(BPMOptionsPage)

    def retranslateUi(self, BPMOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        self.bpm_options.setTitle(_("BPM Analyze Parameters:"))
        self.slider_default.setText(_("Default"))
        self.slider_super_fast.setText(_("Super Fast"))
        self.hop_s_label.setText(_("Number of frames between two consecutive runs:"))
        self.win_s_label.setText(_("Length of FFT:"))
        self.samplerate_label.setText(_("Samplerate:"))
