# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options_album_level_tags.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_AlbumLevelTagsOptionsPage(object):
    def setupUi(self, AlbumLevelTagsOptionsPage):
        AlbumLevelTagsOptionsPage.setObjectName("AlbumLevelTagsOptionsPage")
        AlbumLevelTagsOptionsPage.resize(663, 619)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AlbumLevelTagsOptionsPage.sizePolicy().hasHeightForWidth())
        AlbumLevelTagsOptionsPage.setSizePolicy(sizePolicy)
        AlbumLevelTagsOptionsPage.setMinimumSize(QtCore.QSize(0, 0))
        AlbumLevelTagsOptionsPage.setWindowTitle("")
        self.gridLayout = QtWidgets.QGridLayout(AlbumLevelTagsOptionsPage)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(AlbumLevelTagsOptionsPage)
        self.tabWidget.setObjectName("tabWidget")
        self.options_tab = QtWidgets.QWidget()
        self.options_tab.setObjectName("options_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.options_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.options_tab)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 602, 774))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setHorizontalSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(200, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(200, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 3, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMinimumSize(QtCore.QSize(200, 0))
        self.spinBox.setMinimum(0)
        self.spinBox.setProperty("value", 0)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_5.addWidget(self.spinBox, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 6, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_5.addWidget(self.lineEdit_4, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(200, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 2, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 4, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(200, 0))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setMinimumSize(QtCore.QSize(200, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_5.addWidget(self.lineEdit_5, 7, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMinimumSize(QtCore.QSize(200, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 7, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_5.addWidget(self.lineEdit_2, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setMinimumSize(QtCore.QSize(200, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 8, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_5.addWidget(self.lineEdit_6, 8, 1, 1, 1)
        self.horizontalLayout_14.addLayout(self.gridLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.label6 = QtWidgets.QLabel(self.groupBox)
        self.label6.setObjectName("label6")
        self.verticalLayout.addWidget(self.label6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_3.addWidget(self.lineEdit_7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.checkBox_copy_defaults = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_copy_defaults.setObjectName("checkBox_copy_defaults")
        self.verticalLayout.addWidget(self.checkBox_copy_defaults)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.label_error = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_error.sizePolicy().hasHeightForWidth())
        self.label_error.setSizePolicy(sizePolicy)
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.horizontalLayout.addWidget(self.label_error)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_raw = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_raw.sizePolicy().hasHeightForWidth())
        self.groupBox_raw.setSizePolicy(sizePolicy)
        self.groupBox_raw.setObjectName("groupBox_raw")
        self._4 = QtWidgets.QVBoxLayout(self.groupBox_raw)
        self._4.setContentsMargins(9, 9, 9, 9)
        self._4.setSpacing(2)
        self._4.setObjectName("_4")
        self.plainTextEdit_raw = QtWidgets.QPlainTextEdit(self.groupBox_raw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_raw.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_raw.setSizePolicy(sizePolicy)
        self.plainTextEdit_raw.setMinimumSize(QtCore.QSize(0, 350))
        self.plainTextEdit_raw.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit_raw.setObjectName("plainTextEdit_raw")
        self._4.addWidget(self.plainTextEdit_raw)
        self.horizontalLayout_raw = QtWidgets.QHBoxLayout()
        self.horizontalLayout_raw.setContentsMargins(-1, 2, -1, -1)
        self.horizontalLayout_raw.setSpacing(10)
        self.horizontalLayout_raw.setObjectName("horizontalLayout_raw")
        self.pushButton_valid_raw = QtWidgets.QPushButton(self.groupBox_raw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_valid_raw.sizePolicy().hasHeightForWidth())
        self.pushButton_valid_raw.setSizePolicy(sizePolicy)
        self.pushButton_valid_raw.setObjectName("pushButton_valid_raw")
        self.horizontalLayout_raw.addWidget(self.pushButton_valid_raw)
        self.label_valid_raw = QtWidgets.QLabel(self.groupBox_raw)
        self.label_valid_raw.setWordWrap(True)
        self.label_valid_raw.setObjectName("label_valid_raw")
        self.horizontalLayout_raw.addWidget(self.label_valid_raw)
        self.label_syntax_raw = QtWidgets.QLabel(self.groupBox_raw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_syntax_raw.sizePolicy().hasHeightForWidth())
        self.label_syntax_raw.setSizePolicy(sizePolicy)
        self.label_syntax_raw.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_syntax_raw.setObjectName("label_syntax_raw")
        self.horizontalLayout_raw.addWidget(self.label_syntax_raw)
        self._4.addLayout(self.horizontalLayout_raw)
        self.verticalLayout_2.addWidget(self.groupBox_raw)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.options_tab, "")
        self.replacements_tab = QtWidgets.QWidget()
        self.replacements_tab.setObjectName("replacements_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.replacements_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_raw_2 = QtWidgets.QGroupBox(self.replacements_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_raw_2.sizePolicy().hasHeightForWidth())
        self.groupBox_raw_2.setSizePolicy(sizePolicy)
        self.groupBox_raw_2.setObjectName("groupBox_raw_2")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.groupBox_raw_2)
        self.vboxlayout.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout.setSpacing(2)
        self.vboxlayout.setObjectName("vboxlayout")
        self.plainTextEdit_raw_2 = QtWidgets.QPlainTextEdit(self.groupBox_raw_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_raw_2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_raw_2.setSizePolicy(sizePolicy)
        self.plainTextEdit_raw_2.setObjectName("plainTextEdit_raw_2")
        self.vboxlayout.addWidget(self.plainTextEdit_raw_2)
        self.horizontalLayout_raw_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_raw_2.setContentsMargins(-1, 2, -1, -1)
        self.horizontalLayout_raw_2.setSpacing(10)
        self.horizontalLayout_raw_2.setObjectName("horizontalLayout_raw_2")
        self.pushButton_valid_raw_2 = QtWidgets.QPushButton(self.groupBox_raw_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_valid_raw_2.sizePolicy().hasHeightForWidth())
        self.pushButton_valid_raw_2.setSizePolicy(sizePolicy)
        self.pushButton_valid_raw_2.setObjectName("pushButton_valid_raw_2")
        self.horizontalLayout_raw_2.addWidget(self.pushButton_valid_raw_2)
        self.label_valid_raw_2 = QtWidgets.QLabel(self.groupBox_raw_2)
        self.label_valid_raw_2.setWordWrap(True)
        self.label_valid_raw_2.setObjectName("label_valid_raw_2")
        self.horizontalLayout_raw_2.addWidget(self.label_valid_raw_2)
        self.label_syntax_raw_2 = QtWidgets.QLabel(self.groupBox_raw_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_syntax_raw_2.sizePolicy().hasHeightForWidth())
        self.label_syntax_raw_2.setSizePolicy(sizePolicy)
        self.label_syntax_raw_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_syntax_raw_2.setObjectName("label_syntax_raw_2")
        self.horizontalLayout_raw_2.addWidget(self.label_syntax_raw_2)
        self.vboxlayout.addLayout(self.horizontalLayout_raw_2)
        self.gridLayout_3.addWidget(self.groupBox_raw_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.replacements_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(AlbumLevelTagsOptionsPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AlbumLevelTagsOptionsPage)

    def retranslateUi(self, AlbumLevelTagsOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("AlbumLevelTagsOptionsPage", "Options profile creator ——— move the pointer on an option for more info"))
        self.label_2.setText(_translate("AlbumLevelTagsOptionsPage", "Limit the number of tags:"))
        self.label_4.setText(_translate("AlbumLevelTagsOptionsPage", "Separator:"))
        self.spinBox.setToolTip(_translate("AlbumLevelTagsOptionsPage", "A number which limits the length of the list to the most common tags.\n"
"\n"
"Default: unlimited"))
        self.spinBox.setSpecialValueText(_translate("AlbumLevelTagsOptionsPage", "unlimited"))
        self.label.setText(_translate("AlbumLevelTagsOptionsPage", "Loaded files only?"))
        self.lineEdit_4.setToolTip(_translate("AlbumLevelTagsOptionsPage", "Python formatter string to be used in case the count of a tag is one.\n"
"\n"
"Default: the same as the other formatter string"))
        self.lineEdit_4.setPlaceholderText(_translate("AlbumLevelTagsOptionsPage", "default"))
        self.label_3.setText(_translate("AlbumLevelTagsOptionsPage", "Omitter string:"))
        self.lineEdit.setToolTip(_translate("AlbumLevelTagsOptionsPage", "A string which will be added at the end of the tags in case the\n"
"length limit omitted some tags from being shown.\n"
"\n"
"Default: nothing"))
        self.lineEdit.setPlaceholderText(_translate("AlbumLevelTagsOptionsPage", "none"))
        self.lineEdit_3.setToolTip(_translate("AlbumLevelTagsOptionsPage", "A Python string formatter. \"{0}\" alone means only a tag itself is shown,\n"
"\"{1}\" is the count of the tag.\n"
"\n"
"Exception: for the \"media\" tag, the count is the number of mediums a media\n"
"format appears on.\n"
"\n"
"Defaults:\n"
"\"{0}\" for the album_level_list function.\n"
"\"{:.0f}\" for the album_level_average function."))
        self.lineEdit_3.setPlaceholderText(_translate("AlbumLevelTagsOptionsPage", "default"))
        self.radioButton_2.setToolTip(_translate("AlbumLevelTagsOptionsPage", "Yes: only tracks with files attached to them are looped through when looking for tags.\n"
"No: all tracks are looped through when looking for tags.\n"
"\n"
"Default: No"))
        self.radioButton_2.setText(_translate("AlbumLevelTagsOptionsPage", "Yes"))
        self.radioButton.setToolTip(_translate("AlbumLevelTagsOptionsPage", "Yes: only tracks with files attached to them are looped through when looking for tags.\n"
"No: all tracks are looped through when looking for tags.\n"
"\n"
"Default: No"))
        self.radioButton.setText(_translate("AlbumLevelTagsOptionsPage", "No"))
        self.label_5.setText(_translate("AlbumLevelTagsOptionsPage", "Formatter string:"))
        self.label_6.setText(_translate("AlbumLevelTagsOptionsPage", "Formatter string when count equals one:"))
        self.lineEdit_5.setToolTip(_translate("AlbumLevelTagsOptionsPage", "Only has an effect with the album_level_average function.\n"
"\n"
"Default: no grouping"))
        self.lineEdit_5.setPlaceholderText(_translate("AlbumLevelTagsOptionsPage", "none"))
        self.label_7.setText(_translate("AlbumLevelTagsOptionsPage", "Group the tags by another tag which is:"))
        self.lineEdit_2.setToolTip(_translate("AlbumLevelTagsOptionsPage", "A string added in between multiple tags.\n"
"\n"
"Default: \"; \""))
        self.lineEdit_2.setPlaceholderText(_translate("AlbumLevelTagsOptionsPage", "default"))
        self.label_8.setText(_translate("AlbumLevelTagsOptionsPage", "Replacements profile:"))
        self.lineEdit_6.setToolTip(_translate("AlbumLevelTagsOptionsPage", "See the replacements tab.\n"
"\n"
"Default: no replacements"))
        self.lineEdit_6.setPlaceholderText(_translate("AlbumLevelTagsOptionsPage", "none"))
        self.label6.setText(_translate("AlbumLevelTagsOptionsPage", "Options profile name to which these settings are saved:"))
        self.lineEdit_7.setToolTip(_translate("AlbumLevelTagsOptionsPage", "Options profile name is the optional second parameter of\n"
"$album_level() and $album_level_average()."))
        self.checkBox_copy_defaults.setToolTip(_translate("AlbumLevelTagsOptionsPage", "Makes the raw options harder to read but easier to edit by hand."))
        self.checkBox_copy_defaults.setText(_translate("AlbumLevelTagsOptionsPage", "Copy all options even when they are left at default values"))
        self.pushButton_2.setToolTip(_translate("AlbumLevelTagsOptionsPage", "Add the above settings to an options profile."))
        self.pushButton_2.setText(_translate("AlbumLevelTagsOptionsPage", "Add profile"))
        self.pushButton_3.setToolTip(_translate("AlbumLevelTagsOptionsPage", "Resets the above fields to their defaults."))
        self.pushButton_3.setText(_translate("AlbumLevelTagsOptionsPage", "Reset"))
        self.groupBox_raw.setTitle(_translate("AlbumLevelTagsOptionsPage", "Raw options"))
        self.pushButton_valid_raw.setToolTip(_translate("AlbumLevelTagsOptionsPage", "Checks the syntax and verifies that the options look right.\n"
"Note that the options can still be faulty in other ways."))
        self.pushButton_valid_raw.setText(_translate("AlbumLevelTagsOptionsPage", "Validate"))
        self.label_syntax_raw.setText(_translate("AlbumLevelTagsOptionsPage", "Syntax: JSON"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.options_tab), _translate("AlbumLevelTagsOptionsPage", "Options"))
        self.groupBox_raw_2.setTitle(_translate("AlbumLevelTagsOptionsPage", "Raw replacements"))
        self.pushButton_valid_raw_2.setToolTip(_translate("AlbumLevelTagsOptionsPage", "Checks the syntax."))
        self.pushButton_valid_raw_2.setText(_translate("AlbumLevelTagsOptionsPage", "Validate"))
        self.label_syntax_raw_2.setText(_translate("AlbumLevelTagsOptionsPage", "Syntax: JSON"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.replacements_tab), _translate("AlbumLevelTagsOptionsPage", "Replacements"))
