# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PerformerTagReplaceOptionsPage(object):
    def setupUi(self, PerformerTagReplaceOptionsPage):
        PerformerTagReplaceOptionsPage.setObjectName("PerformerTagReplaceOptionsPage")
        PerformerTagReplaceOptionsPage.resize(398, 568)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PerformerTagReplaceOptionsPage.sizePolicy().hasHeightForWidth())
        PerformerTagReplaceOptionsPage.setSizePolicy(sizePolicy)
        self.vboxlayout = QtWidgets.QVBoxLayout(PerformerTagReplaceOptionsPage)
        self.vboxlayout.setSpacing(16)
        self.vboxlayout.setObjectName("vboxlayout")
        self.scrollArea = QtWidgets.QScrollArea(PerformerTagReplaceOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(380, 550))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 380, 550))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gb_description = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_description.sizePolicy().hasHeightForWidth())
        self.gb_description.setSizePolicy(sizePolicy)
        self.gb_description.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gb_description.setFont(font)
        self.gb_description.setObjectName("gb_description")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gb_description)
        self.verticalLayout.setContentsMargins(9, 9, 9, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.format_description = QtWidgets.QLabel(self.gb_description)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_description.sizePolicy().hasHeightForWidth())
        self.format_description.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.format_description.setFont(font)
        self.format_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.format_description.setWordWrap(True)
        self.format_description.setObjectName("format_description")
        self.verticalLayout.addWidget(self.format_description)
        self.verticalLayout_2.addWidget(self.gb_description)
        self.gb_replacement_pairs = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gb_replacement_pairs.setFont(font)
        self.gb_replacement_pairs.setObjectName("gb_replacement_pairs")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gb_replacement_pairs)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.performer_tag_replacement_pairs = QtWidgets.QPlainTextEdit(self.gb_replacement_pairs)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.performer_tag_replacement_pairs.setFont(font)
        self.performer_tag_replacement_pairs.setObjectName("performer_tag_replacement_pairs")
        self.verticalLayout_3.addWidget(self.performer_tag_replacement_pairs)
        self.verticalLayout_2.addWidget(self.gb_replacement_pairs, 0, QtCore.Qt.AlignTop)
        self.performer_tag_replace_performers = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.performer_tag_replace_performers.setChecked(False)
        self.performer_tag_replace_performers.setObjectName("performer_tag_replace_performers")
        self.verticalLayout_2.addWidget(self.performer_tag_replace_performers)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.vboxlayout.addWidget(self.scrollArea, 0, QtCore.Qt.AlignTop)

        self.retranslateUi(PerformerTagReplaceOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(PerformerTagReplaceOptionsPage)

    def retranslateUi(self, PerformerTagReplaceOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        self.gb_description.setTitle(_("Performer Tag Replacement"))
        self.format_description.setText(_("<html><head/><body><p>These are the original / replacement pairs used to modify the keys for the performer tags. Each pair must be entered on a separate line in the form:</p><p><span style=\" font-weight:600;\">original character string=replacement character string</span></p><p>Blank lines and lines beginning with an equals sign (=) will be ignored. Replacements will be made in the order they are found in the list. An example for removing &quot;family&quot; from instrument names would be done using the following two lines:</p><pre style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:10pt; font-weight:600;\">s family=ses<br/> family=s</span></pre><p>Note that the second line begins with a single space.</p><p>For more information please see the <a href=\"https://github.com/rdswift/picard-plugins/blob/2.0_RDS_Plugins/plugins/performer_tag_replace/docs/README.md\"><span style=\" text-decoration: underline; color:#0000ff;\">User Guide</span></a> on GitHub.<br/></p></body></html>"))
        self.gb_replacement_pairs.setTitle(_("Replacement Pairs"))
        self.performer_tag_replacement_pairs.setPlaceholderText(_("Enter replacement pairs (one per line)"))
        self.performer_tag_replace_performers.setText(_("Apply replacements to performers as well as instruments && vocals"))

