# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options_wikidata.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WikidataOptionsPage(object):
    def setupUi(self, WikidataOptionsPage):
        WikidataOptionsPage.setObjectName("WikidataOptionsPage")
        WikidataOptionsPage.resize(602, 512)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WikidataOptionsPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(WikidataOptionsPage)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.use_release_group_genres = QtWidgets.QCheckBox(self.groupBox)
        self.use_release_group_genres.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_release_group_genres.sizePolicy().hasHeightForWidth())
        self.use_release_group_genres.setSizePolicy(sizePolicy)
        self.use_release_group_genres.setChecked(True)
        self.use_release_group_genres.setObjectName("use_release_group_genres")
        self.verticalLayout_4.addWidget(self.use_release_group_genres)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(WikidataOptionsPage)
        self.groupBox_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.use_artist_genres = QtWidgets.QCheckBox(self.groupBox_2)
        self.use_artist_genres.setObjectName("use_artist_genres")
        self.verticalLayout_8.addWidget(self.use_artist_genres)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.use_artist_only_if_no_release = QtWidgets.QCheckBox(self.groupBox_2)
        self.use_artist_only_if_no_release.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_artist_only_if_no_release.sizePolicy().hasHeightForWidth())
        self.use_artist_only_if_no_release.setSizePolicy(sizePolicy)
        self.use_artist_only_if_no_release.setCheckable(True)
        self.use_artist_only_if_no_release.setChecked(False)
        self.use_artist_only_if_no_release.setObjectName("use_artist_only_if_no_release")
        self.horizontalLayout_4.addWidget(self.use_artist_only_if_no_release)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.ignore_genres_from_these_artists_label = QtWidgets.QLabel(self.groupBox_2)
        self.ignore_genres_from_these_artists_label.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ignore_genres_from_these_artists_label.sizePolicy().hasHeightForWidth())
        self.ignore_genres_from_these_artists_label.setSizePolicy(sizePolicy)
        self.ignore_genres_from_these_artists_label.setObjectName("ignore_genres_from_these_artists_label")
        self.horizontalLayout_2.addWidget(self.ignore_genres_from_these_artists_label)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.ignore_genres_from_these_artists = QtWidgets.QLineEdit(self.groupBox_2)
        self.ignore_genres_from_these_artists.setEnabled(False)
        self.ignore_genres_from_these_artists.setObjectName("ignore_genres_from_these_artists")
        self.horizontalLayout_3.addWidget(self.ignore_genres_from_these_artists)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.wikidata_vert_layout = QtWidgets.QGroupBox(WikidataOptionsPage)
        self.wikidata_vert_layout.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wikidata_vert_layout.sizePolicy().hasHeightForWidth())
        self.wikidata_vert_layout.setSizePolicy(sizePolicy)
        self.wikidata_vert_layout.setObjectName("wikidata_vert_layout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.wikidata_vert_layout)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.use_work_genres = QtWidgets.QCheckBox(self.wikidata_vert_layout)
        self.use_work_genres.setChecked(True)
        self.use_work_genres.setObjectName("use_work_genres")
        self.verticalLayout_3.addWidget(self.use_work_genres)
        self.verticalLayout_2.addWidget(self.wikidata_vert_layout)
        self.groupBox_3 = QtWidgets.QGroupBox(WikidataOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_4 = QtWidgets.QFrame(self.groupBox_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.ignore_genres_label = QtWidgets.QLabel(self.groupBox_3)
        self.ignore_genres_label.setObjectName("ignore_genres_label")
        self.verticalLayout.addWidget(self.ignore_genres_label)
        self.ignore_these_genres = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ignore_these_genres.sizePolicy().hasHeightForWidth())
        self.ignore_these_genres.setSizePolicy(sizePolicy)
        self.ignore_these_genres.setObjectName("ignore_these_genres")
        self.verticalLayout.addWidget(self.ignore_these_genres)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.genre_delimiter_label = QtWidgets.QLabel(self.groupBox_3)
        self.genre_delimiter_label.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genre_delimiter_label.sizePolicy().hasHeightForWidth())
        self.genre_delimiter_label.setSizePolicy(sizePolicy)
        self.genre_delimiter_label.setWordWrap(False)
        self.genre_delimiter_label.setObjectName("genre_delimiter_label")
        self.horizontalLayout_5.addWidget(self.genre_delimiter_label)
        self.genre_delimiter = QtWidgets.QComboBox(self.groupBox_3)
        self.genre_delimiter.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genre_delimiter.sizePolicy().hasHeightForWidth())
        self.genre_delimiter.setSizePolicy(sizePolicy)
        self.genre_delimiter.setEditable(True)
        self.genre_delimiter.setObjectName("genre_delimiter")
        self.genre_delimiter.addItem("")
        self.genre_delimiter.setItemText(0, " / ")
        self.genre_delimiter.addItem("")
        self.genre_delimiter.addItem("")
        self.genre_delimiter.setItemText(2, ";")
        self.genre_delimiter.addItem("")
        self.genre_delimiter.addItem("")
        self.genre_delimiter.setItemText(4, ", ")
        self.horizontalLayout_5.addWidget(self.genre_delimiter)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.genre_delimiter_note = QtWidgets.QLabel(self.groupBox_3)
        self.genre_delimiter_note.setEnabled(False)
        self.genre_delimiter_note.setObjectName("genre_delimiter_note")
        self.horizontalLayout_5.addWidget(self.genre_delimiter_note)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)

        self.retranslateUi(WikidataOptionsPage)
        self.use_artist_genres.toggled['bool'].connect(self.ignore_genres_from_these_artists_label.setEnabled)
        self.use_artist_genres.toggled['bool'].connect(self.use_artist_only_if_no_release.setEnabled)
        self.use_artist_genres.toggled['bool'].connect(self.ignore_genres_from_these_artists.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(WikidataOptionsPage)

    def retranslateUi(self, WikidataOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("WikidataOptionsPage", "Release Group Genre Settings"))
        self.use_release_group_genres.setText(_translate("WikidataOptionsPage", "Use Release Group genres"))
        self.groupBox_2.setTitle(_translate("WikidataOptionsPage", "Artist Genre Settings"))
        self.use_artist_genres.setText(_translate("WikidataOptionsPage", "Use Artist genres"))
        self.use_artist_only_if_no_release.setText(_translate("WikidataOptionsPage", "Use Artist genres only if no Release Group genres exist"))
        self.ignore_genres_from_these_artists_label.setText(_translate("WikidataOptionsPage", "Ignore Artist genres from these Artist(s):  (comma separated regular expressions)"))
        self.wikidata_vert_layout.setTitle(_translate("WikidataOptionsPage", "Work Genre Settings"))
        self.use_work_genres.setText(_translate("WikidataOptionsPage", "Use Work genres, when applicable"))
        self.groupBox_3.setTitle(_translate("WikidataOptionsPage", "General Settings"))
        self.ignore_genres_label.setText(_translate("WikidataOptionsPage", "Ignore these genres:   (comma separated regular expressions)"))
        self.genre_delimiter_label.setText(_translate("WikidataOptionsPage", "Genre Delimiter:"))
        self.genre_delimiter.setItemText(1, _translate("WikidataOptionsPage", "; "))
        self.genre_delimiter.setItemText(3, _translate("WikidataOptionsPage", " ; "))
        self.genre_delimiter_note.setText(_translate("WikidataOptionsPage", "(only applicable to ID3v2.3 tags)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WikidataOptionsPage = QtWidgets.QWidget()
    ui = Ui_WikidataOptionsPage()
    ui.setupUi(WikidataOptionsPage)
    WikidataOptionsPage.show()
    sys.exit(app.exec_())

