# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormatPerformerTagsOptionsPage(object):
    def setupUi(self, FormatPerformerTagsOptionsPage):
        FormatPerformerTagsOptionsPage.setObjectName("FormatPerformerTagsOptionsPage")
        FormatPerformerTagsOptionsPage.resize(458, 673)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FormatPerformerTagsOptionsPage.sizePolicy().hasHeightForWidth())
        FormatPerformerTagsOptionsPage.setSizePolicy(sizePolicy)
        self.vboxlayout = QtWidgets.QVBoxLayout(FormatPerformerTagsOptionsPage)
        self.vboxlayout.setSpacing(16)
        self.vboxlayout.setObjectName("vboxlayout")
        self.scrollArea = QtWidgets.QScrollArea(FormatPerformerTagsOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(440, 655))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 440, 655))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gb_description = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_description.sizePolicy().hasHeightForWidth())
        self.gb_description.setSizePolicy(sizePolicy)
        self.gb_description.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gb_description.setFont(font)
        self.gb_description.setObjectName("gb_description")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gb_description)
        self.verticalLayout.setContentsMargins(9, 9, 9, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.format_description = QtWidgets.QLabel(self.gb_description)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_description.sizePolicy().hasHeightForWidth())
        self.format_description.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.format_description.setFont(font)
        self.format_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.format_description.setWordWrap(True)
        self.format_description.setObjectName("format_description")
        self.verticalLayout.addWidget(self.format_description)
        self.verticalLayout_2.addWidget(self.gb_description)
        self.gb_word_groups = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gb_word_groups.setFont(font)
        self.gb_word_groups.setObjectName("gb_word_groups")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gb_word_groups)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.group_additional = QtWidgets.QGroupBox(self.gb_word_groups)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_additional.sizePolicy().hasHeightForWidth())
        self.group_additional.setSizePolicy(sizePolicy)
        self.group_additional.setMinimumSize(QtCore.QSize(0, 0))
        self.group_additional.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.group_additional.setFont(font)
        self.group_additional.setObjectName("group_additional")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.group_additional)
        self.horizontalLayout_2.setContentsMargins(1, 0, 1, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.additional_rb_1 = QtWidgets.QRadioButton(self.group_additional)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.additional_rb_1.sizePolicy().hasHeightForWidth())
        self.additional_rb_1.setSizePolicy(sizePolicy)
        self.additional_rb_1.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.additional_rb_1.setFont(font)
        self.additional_rb_1.setChecked(False)
        self.additional_rb_1.setObjectName("additional_rb_1")
        self.horizontalLayout_2.addWidget(self.additional_rb_1, 0, QtCore.Qt.AlignVCenter)
        self.additional_rb_2 = QtWidgets.QRadioButton(self.group_additional)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.additional_rb_2.sizePolicy().hasHeightForWidth())
        self.additional_rb_2.setSizePolicy(sizePolicy)
        self.additional_rb_2.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.additional_rb_2.setFont(font)
        self.additional_rb_2.setObjectName("additional_rb_2")
        self.horizontalLayout_2.addWidget(self.additional_rb_2, 0, QtCore.Qt.AlignVCenter)
        self.additional_rb_3 = QtWidgets.QRadioButton(self.group_additional)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.additional_rb_3.sizePolicy().hasHeightForWidth())
        self.additional_rb_3.setSizePolicy(sizePolicy)
        self.additional_rb_3.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.additional_rb_3.setFont(font)
        self.additional_rb_3.setChecked(True)
        self.additional_rb_3.setObjectName("additional_rb_3")
        self.horizontalLayout_2.addWidget(self.additional_rb_3, 0, QtCore.Qt.AlignVCenter)
        self.additional_rb_4 = QtWidgets.QRadioButton(self.group_additional)
        self.additional_rb_4.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.additional_rb_4.setFont(font)
        self.additional_rb_4.setObjectName("additional_rb_4")
        self.horizontalLayout_2.addWidget(self.additional_rb_4, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_3.addWidget(self.group_additional)
        self.group_guest = QtWidgets.QGroupBox(self.gb_word_groups)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_guest.sizePolicy().hasHeightForWidth())
        self.group_guest.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.group_guest.setFont(font)
        self.group_guest.setObjectName("group_guest")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.group_guest)
        self.horizontalLayout_3.setContentsMargins(1, 0, 1, 0)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.guest_rb_1 = QtWidgets.QRadioButton(self.group_guest)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guest_rb_1.sizePolicy().hasHeightForWidth())
        self.guest_rb_1.setSizePolicy(sizePolicy)
        self.guest_rb_1.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.guest_rb_1.setFont(font)
        self.guest_rb_1.setChecked(False)
        self.guest_rb_1.setObjectName("guest_rb_1")
        self.horizontalLayout_3.addWidget(self.guest_rb_1, 0, QtCore.Qt.AlignVCenter)
        self.guest_rb_2 = QtWidgets.QRadioButton(self.group_guest)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guest_rb_2.sizePolicy().hasHeightForWidth())
        self.guest_rb_2.setSizePolicy(sizePolicy)
        self.guest_rb_2.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.guest_rb_2.setFont(font)
        self.guest_rb_2.setObjectName("guest_rb_2")
        self.horizontalLayout_3.addWidget(self.guest_rb_2, 0, QtCore.Qt.AlignVCenter)
        self.guest_rb_3 = QtWidgets.QRadioButton(self.group_guest)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guest_rb_3.sizePolicy().hasHeightForWidth())
        self.guest_rb_3.setSizePolicy(sizePolicy)
        self.guest_rb_3.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.guest_rb_3.setFont(font)
        self.guest_rb_3.setObjectName("guest_rb_3")
        self.horizontalLayout_3.addWidget(self.guest_rb_3, 0, QtCore.Qt.AlignVCenter)
        self.guest_rb_4 = QtWidgets.QRadioButton(self.group_guest)
        self.guest_rb_4.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.guest_rb_4.setFont(font)
        self.guest_rb_4.setChecked(True)
        self.guest_rb_4.setObjectName("guest_rb_4")
        self.horizontalLayout_3.addWidget(self.guest_rb_4, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_3.addWidget(self.group_guest)
        self.group_solo = QtWidgets.QGroupBox(self.gb_word_groups)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_solo.sizePolicy().hasHeightForWidth())
        self.group_solo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.group_solo.setFont(font)
        self.group_solo.setObjectName("group_solo")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.group_solo)
        self.horizontalLayout_4.setContentsMargins(1, 0, 1, 0)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.solo_rb_1 = QtWidgets.QRadioButton(self.group_solo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solo_rb_1.sizePolicy().hasHeightForWidth())
        self.solo_rb_1.setSizePolicy(sizePolicy)
        self.solo_rb_1.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.solo_rb_1.setFont(font)
        self.solo_rb_1.setChecked(False)
        self.solo_rb_1.setObjectName("solo_rb_1")
        self.horizontalLayout_4.addWidget(self.solo_rb_1, 0, QtCore.Qt.AlignVCenter)
        self.solo_rb_2 = QtWidgets.QRadioButton(self.group_solo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solo_rb_2.sizePolicy().hasHeightForWidth())
        self.solo_rb_2.setSizePolicy(sizePolicy)
        self.solo_rb_2.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.solo_rb_2.setFont(font)
        self.solo_rb_2.setObjectName("solo_rb_2")
        self.horizontalLayout_4.addWidget(self.solo_rb_2, 0, QtCore.Qt.AlignVCenter)
        self.solo_rb_3 = QtWidgets.QRadioButton(self.group_solo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solo_rb_3.sizePolicy().hasHeightForWidth())
        self.solo_rb_3.setSizePolicy(sizePolicy)
        self.solo_rb_3.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.solo_rb_3.setFont(font)
        self.solo_rb_3.setChecked(True)
        self.solo_rb_3.setObjectName("solo_rb_3")
        self.horizontalLayout_4.addWidget(self.solo_rb_3, 0, QtCore.Qt.AlignVCenter)
        self.solo_rb_4 = QtWidgets.QRadioButton(self.group_solo)
        self.solo_rb_4.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.solo_rb_4.setFont(font)
        self.solo_rb_4.setObjectName("solo_rb_4")
        self.horizontalLayout_4.addWidget(self.solo_rb_4, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_3.addWidget(self.group_solo)
        self.group_vocals = QtWidgets.QGroupBox(self.gb_word_groups)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_vocals.sizePolicy().hasHeightForWidth())
        self.group_vocals.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.group_vocals.setFont(font)
        self.group_vocals.setObjectName("group_vocals")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.group_vocals)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.vocals_rb_1 = QtWidgets.QRadioButton(self.group_vocals)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vocals_rb_1.sizePolicy().hasHeightForWidth())
        self.vocals_rb_1.setSizePolicy(sizePolicy)
        self.vocals_rb_1.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vocals_rb_1.setFont(font)
        self.vocals_rb_1.setChecked(False)
        self.vocals_rb_1.setObjectName("vocals_rb_1")
        self.horizontalLayout_5.addWidget(self.vocals_rb_1, 0, QtCore.Qt.AlignVCenter)
        self.vocals_rb_2 = QtWidgets.QRadioButton(self.group_vocals)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vocals_rb_2.sizePolicy().hasHeightForWidth())
        self.vocals_rb_2.setSizePolicy(sizePolicy)
        self.vocals_rb_2.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vocals_rb_2.setFont(font)
        self.vocals_rb_2.setChecked(True)
        self.vocals_rb_2.setObjectName("vocals_rb_2")
        self.horizontalLayout_5.addWidget(self.vocals_rb_2, 0, QtCore.Qt.AlignVCenter)
        self.vocals_rb_3 = QtWidgets.QRadioButton(self.group_vocals)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vocals_rb_3.sizePolicy().hasHeightForWidth())
        self.vocals_rb_3.setSizePolicy(sizePolicy)
        self.vocals_rb_3.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vocals_rb_3.setFont(font)
        self.vocals_rb_3.setObjectName("vocals_rb_3")
        self.horizontalLayout_5.addWidget(self.vocals_rb_3, 0, QtCore.Qt.AlignVCenter)
        self.vocals_rb_4 = QtWidgets.QRadioButton(self.group_vocals)
        self.vocals_rb_4.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vocals_rb_4.setFont(font)
        self.vocals_rb_4.setObjectName("vocals_rb_4")
        self.horizontalLayout_5.addWidget(self.vocals_rb_4, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_3.addWidget(self.group_vocals)
        self.verticalLayout_2.addWidget(self.gb_word_groups, 0, QtCore.Qt.AlignTop)
        self.gb_group_settings = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.gb_group_settings.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gb_group_settings.setFont(font)
        self.gb_group_settings.setObjectName("gb_group_settings")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gb_group_settings)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.format_group_3_sep_char = QtWidgets.QLineEdit(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_group_3_sep_char.sizePolicy().hasHeightForWidth())
        self.format_group_3_sep_char.setSizePolicy(sizePolicy)
        self.format_group_3_sep_char.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.format_group_3_sep_char.setFont(font)
        self.format_group_3_sep_char.setObjectName("format_group_3_sep_char")
        self.gridLayout.addWidget(self.format_group_3_sep_char, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.format_group_1_start_char = QtWidgets.QLineEdit(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_group_1_start_char.sizePolicy().hasHeightForWidth())
        self.format_group_1_start_char.setSizePolicy(sizePolicy)
        self.format_group_1_start_char.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.format_group_1_start_char.setFont(font)
        self.format_group_1_start_char.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.format_group_1_start_char.setClearButtonEnabled(False)
        self.format_group_1_start_char.setObjectName("format_group_1_start_char")
        self.gridLayout.addWidget(self.format_group_1_start_char, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.format_group_1_sep_char = QtWidgets.QLineEdit(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_group_1_sep_char.sizePolicy().hasHeightForWidth())
        self.format_group_1_sep_char.setSizePolicy(sizePolicy)
        self.format_group_1_sep_char.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.format_group_1_sep_char.setFont(font)
        self.format_group_1_sep_char.setObjectName("format_group_1_sep_char")
        self.gridLayout.addWidget(self.format_group_1_sep_char, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_18 = QtWidgets.QLabel(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 3, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.format_group_4_start_char = QtWidgets.QLineEdit(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_group_4_start_char.sizePolicy().hasHeightForWidth())
        self.format_group_4_start_char.setSizePolicy(sizePolicy)
        self.format_group_4_start_char.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.format_group_4_start_char.setFont(font)
        self.format_group_4_start_char.setObjectName("format_group_4_start_char")
        self.gridLayout.addWidget(self.format_group_4_start_char, 4, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.format_group_1_end_char = QtWidgets.QLineEdit(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_group_1_end_char.sizePolicy().hasHeightForWidth())
        self.format_group_1_end_char.setSizePolicy(sizePolicy)
        self.format_group_1_end_char.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.format_group_1_end_char.setFont(font)
        self.format_group_1_end_char.setObjectName("format_group_1_end_char")
        self.gridLayout.addWidget(self.format_group_1_end_char, 1, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.format_group_3_start_char = QtWidgets.QLineEdit(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_group_3_start_char.sizePolicy().hasHeightForWidth())
        self.format_group_3_start_char.setSizePolicy(sizePolicy)
        self.format_group_3_start_char.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.format_group_3_start_char.setFont(font)
        self.format_group_3_start_char.setObjectName("format_group_3_start_char")
        self.gridLayout.addWidget(self.format_group_3_start_char, 3, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label = QtWidgets.QLabel(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.format_group_4_sep_char = QtWidgets.QLineEdit(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_group_4_sep_char.sizePolicy().hasHeightForWidth())
        self.format_group_4_sep_char.setSizePolicy(sizePolicy)
        self.format_group_4_sep_char.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.format_group_4_sep_char.setFont(font)
        self.format_group_4_sep_char.setObjectName("format_group_4_sep_char")
        self.gridLayout.addWidget(self.format_group_4_sep_char, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_19 = QtWidgets.QLabel(self.gb_group_settings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.format_group_2_sep_char = QtWidgets.QLineEdit(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_group_2_sep_char.sizePolicy().hasHeightForWidth())
        self.format_group_2_sep_char.setSizePolicy(sizePolicy)
        self.format_group_2_sep_char.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.format_group_2_sep_char.setFont(font)
        self.format_group_2_sep_char.setObjectName("format_group_2_sep_char")
        self.gridLayout.addWidget(self.format_group_2_sep_char, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_20 = QtWidgets.QLabel(self.gb_group_settings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 2, 1, 1)
        self.format_group_4_end_char = QtWidgets.QLineEdit(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_group_4_end_char.sizePolicy().hasHeightForWidth())
        self.format_group_4_end_char.setSizePolicy(sizePolicy)
        self.format_group_4_end_char.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.format_group_4_end_char.setFont(font)
        self.format_group_4_end_char.setObjectName("format_group_4_end_char")
        self.gridLayout.addWidget(self.format_group_4_end_char, 4, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_15 = QtWidgets.QLabel(self.gb_group_settings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.format_group_2_end_char = QtWidgets.QLineEdit(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_group_2_end_char.sizePolicy().hasHeightForWidth())
        self.format_group_2_end_char.setSizePolicy(sizePolicy)
        self.format_group_2_end_char.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.format_group_2_end_char.setFont(font)
        self.format_group_2_end_char.setText("")
        self.format_group_2_end_char.setObjectName("format_group_2_end_char")
        self.gridLayout.addWidget(self.format_group_2_end_char, 2, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_5 = QtWidgets.QLabel(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.format_group_3_end_char = QtWidgets.QLineEdit(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_group_3_end_char.sizePolicy().hasHeightForWidth())
        self.format_group_3_end_char.setSizePolicy(sizePolicy)
        self.format_group_3_end_char.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.format_group_3_end_char.setFont(font)
        self.format_group_3_end_char.setObjectName("format_group_3_end_char")
        self.gridLayout.addWidget(self.format_group_3_end_char, 3, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.format_group_2_start_char = QtWidgets.QLineEdit(self.gb_group_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_group_2_start_char.sizePolicy().hasHeightForWidth())
        self.format_group_2_start_char.setSizePolicy(sizePolicy)
        self.format_group_2_start_char.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.format_group_2_start_char.setFont(font)
        self.format_group_2_start_char.setObjectName("format_group_2_start_char")
        self.gridLayout.addWidget(self.format_group_2_start_char, 2, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.gb_group_settings)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.vboxlayout.addWidget(self.scrollArea, 0, QtCore.Qt.AlignTop)

        self.retranslateUi(FormatPerformerTagsOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(FormatPerformerTagsOptionsPage)
        FormatPerformerTagsOptionsPage.setTabOrder(self.additional_rb_1, self.additional_rb_2)
        FormatPerformerTagsOptionsPage.setTabOrder(self.additional_rb_2, self.additional_rb_3)
        FormatPerformerTagsOptionsPage.setTabOrder(self.additional_rb_3, self.additional_rb_4)
        FormatPerformerTagsOptionsPage.setTabOrder(self.additional_rb_4, self.guest_rb_1)
        FormatPerformerTagsOptionsPage.setTabOrder(self.guest_rb_1, self.guest_rb_2)
        FormatPerformerTagsOptionsPage.setTabOrder(self.guest_rb_2, self.guest_rb_3)
        FormatPerformerTagsOptionsPage.setTabOrder(self.guest_rb_3, self.guest_rb_4)
        FormatPerformerTagsOptionsPage.setTabOrder(self.guest_rb_4, self.solo_rb_1)
        FormatPerformerTagsOptionsPage.setTabOrder(self.solo_rb_1, self.solo_rb_2)
        FormatPerformerTagsOptionsPage.setTabOrder(self.solo_rb_2, self.solo_rb_3)
        FormatPerformerTagsOptionsPage.setTabOrder(self.solo_rb_3, self.solo_rb_4)
        FormatPerformerTagsOptionsPage.setTabOrder(self.solo_rb_4, self.vocals_rb_1)
        FormatPerformerTagsOptionsPage.setTabOrder(self.vocals_rb_1, self.vocals_rb_2)
        FormatPerformerTagsOptionsPage.setTabOrder(self.vocals_rb_2, self.vocals_rb_3)
        FormatPerformerTagsOptionsPage.setTabOrder(self.vocals_rb_3, self.vocals_rb_4)
        FormatPerformerTagsOptionsPage.setTabOrder(self.vocals_rb_4, self.format_group_1_start_char)
        FormatPerformerTagsOptionsPage.setTabOrder(self.format_group_1_start_char, self.format_group_1_sep_char)
        FormatPerformerTagsOptionsPage.setTabOrder(self.format_group_1_sep_char, self.format_group_1_end_char)
        FormatPerformerTagsOptionsPage.setTabOrder(self.format_group_1_end_char, self.format_group_2_start_char)
        FormatPerformerTagsOptionsPage.setTabOrder(self.format_group_2_start_char, self.format_group_2_sep_char)
        FormatPerformerTagsOptionsPage.setTabOrder(self.format_group_2_sep_char, self.format_group_2_end_char)
        FormatPerformerTagsOptionsPage.setTabOrder(self.format_group_2_end_char, self.format_group_3_start_char)
        FormatPerformerTagsOptionsPage.setTabOrder(self.format_group_3_start_char, self.format_group_3_sep_char)
        FormatPerformerTagsOptionsPage.setTabOrder(self.format_group_3_sep_char, self.format_group_3_end_char)
        FormatPerformerTagsOptionsPage.setTabOrder(self.format_group_3_end_char, self.format_group_4_start_char)
        FormatPerformerTagsOptionsPage.setTabOrder(self.format_group_4_start_char, self.format_group_4_sep_char)
        FormatPerformerTagsOptionsPage.setTabOrder(self.format_group_4_sep_char, self.format_group_4_end_char)
        FormatPerformerTagsOptionsPage.setTabOrder(self.format_group_4_end_char, self.scrollArea)

    def retranslateUi(self, FormatPerformerTagsOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        self.gb_description.setTitle(_("Format Performer Tags"))
        self.format_description.setText(_("<html><head/><body><p>These settings will determine the format for any <span style=\" font-weight:600;\">Performer</span> tags prepared. The format is divided into six parts: the performer; the instrument or &quot;vocals&quot;; and four user selectable sections for the extra information. This is set out as:</p><p align=\"center\"><span style=\" font-weight:600;\">[Section 1]</span>Instrument/Vocals<span style=\" font-weight:600;\">[Section 2][Section 3]</span>: Performer<span style=\" font-weight:600;\">[Section 4]</span></p><p>You can select the section in which each of the extra information words appears.</p><p>For each of the sections you can select the starting character(s), the character(s) separating entries, and the ending character(s). Note that leading or trailing spaces must be included in the settings and will not be automatically added. If no separator characters are entered, the items within a section will be automatically separated by a single space.</p><p>Please visit the repository on GitHub for <a href=\"https://github.com/rdswift/picard-plugins/blob/2.0_RDS_Plugins/plugins/format_performer_tags/docs/README.md\"><span style=\" text-decoration: underline; color:#0000ff;\">additional information</span></a>.</p></body></html>"))
        self.gb_word_groups.setTitle(_("Keyword Section Assignments"))
        self.group_additional.setTitle(_("Keyword: additional"))
        self.additional_rb_1.setText(_("1"))
        self.additional_rb_2.setText(_("2"))
        self.additional_rb_3.setText(_("3"))
        self.additional_rb_4.setText(_("4"))
        self.group_guest.setTitle(_("Keyword: guest"))
        self.guest_rb_1.setText(_("1"))
        self.guest_rb_2.setText(_("2"))
        self.guest_rb_3.setText(_("3"))
        self.guest_rb_4.setText(_("4"))
        self.group_solo.setTitle(_("Keyword: solo"))
        self.solo_rb_1.setText(_("1"))
        self.solo_rb_2.setText(_("2"))
        self.solo_rb_3.setText(_("3"))
        self.solo_rb_4.setText(_("4"))
        self.group_vocals.setTitle(_("All vocal type keywords"))
        self.vocals_rb_1.setText(_("1"))
        self.vocals_rb_2.setText(_("2"))
        self.vocals_rb_3.setText(_("3"))
        self.vocals_rb_4.setText(_("4"))
        self.gb_group_settings.setTitle(_("Section Display Settings"))
        self.format_group_3_sep_char.setPlaceholderText(_("(blank)"))
        self.format_group_1_start_char.setPlaceholderText(_("(blank)"))
        self.format_group_1_sep_char.setPlaceholderText(_("(blank)"))
        self.label_18.setText(_("Section 3 "))
        self.format_group_4_start_char.setText(_(" ("))
        self.format_group_4_start_char.setPlaceholderText(_("(blank)"))
        self.format_group_1_end_char.setPlaceholderText(_("(blank)"))
        self.format_group_3_start_char.setText(_(" ("))
        self.format_group_3_start_char.setPlaceholderText(_("(blank)"))
        self.label.setText(_("Section 2 "))
        self.format_group_4_sep_char.setPlaceholderText(_("(blank)"))
        self.label_19.setText(_("End Char(s)"))
        self.label_7.setText(_("Section 4 "))
        self.format_group_2_sep_char.setPlaceholderText(_("(blank)"))
        self.label_20.setText(_("Sep Char(s)"))
        self.format_group_4_end_char.setText(_(")"))
        self.format_group_4_end_char.setPlaceholderText(_("(blank)"))
        self.label_15.setText(_("Start Char(s)"))
        self.format_group_2_end_char.setPlaceholderText(_("(blank)"))
        self.label_5.setText(_("Section 1 "))
        self.format_group_3_end_char.setText(_(")"))
        self.format_group_3_end_char.setPlaceholderText(_("(blank)"))
        self.format_group_2_start_char.setText(_(", "))
        self.format_group_2_start_char.setPlaceholderText(_("(blank)"))

