# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\phw\devel\musicbrainz\picard-plugins\plugins\acousticbrainz\ui_options_acousticbrainz_tags.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AcousticbrainzOptionsPage(object):
    def setupUi(self, AcousticbrainzOptionsPage):
        AcousticbrainzOptionsPage.setObjectName("AcousticbrainzOptionsPage")
        AcousticbrainzOptionsPage.setEnabled(True)
        AcousticbrainzOptionsPage.resize(527, 443)
        AcousticbrainzOptionsPage.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(AcousticbrainzOptionsPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.acousticbrainzTags_groupBox = QtWidgets.QGroupBox(AcousticbrainzOptionsPage)
        self.acousticbrainzTags_groupBox.setObjectName("acousticbrainzTags_groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.acousticbrainzTags_groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.add_simplemood = QtWidgets.QCheckBox(self.acousticbrainzTags_groupBox)
        self.add_simplemood.setObjectName("add_simplemood")
        self.verticalLayout_2.addWidget(self.add_simplemood)
        self.add_simplegenre = QtWidgets.QCheckBox(self.acousticbrainzTags_groupBox)
        self.add_simplegenre.setObjectName("add_simplegenre")
        self.verticalLayout_2.addWidget(self.add_simplegenre)
        self.add_keybpm = QtWidgets.QCheckBox(self.acousticbrainzTags_groupBox)
        self.add_keybpm.setObjectName("add_keybpm")
        self.verticalLayout_2.addWidget(self.add_keybpm)
        self.add_fullhighlevel = QtWidgets.QCheckBox(self.acousticbrainzTags_groupBox)
        self.add_fullhighlevel.setObjectName("add_fullhighlevel")
        self.verticalLayout_2.addWidget(self.add_fullhighlevel)
        self.add_sublowlevel = QtWidgets.QCheckBox(self.acousticbrainzTags_groupBox)
        self.add_sublowlevel.setObjectName("add_sublowlevel")
        self.verticalLayout_2.addWidget(self.add_sublowlevel)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem)
        self.sublowlevel_descr = QtWidgets.QLabel(self.acousticbrainzTags_groupBox)
        self.sublowlevel_descr.setTextFormat(QtCore.Qt.RichText)
        self.sublowlevel_descr.setObjectName("sublowlevel_descr")
        self.verticalLayout_2.addWidget(self.sublowlevel_descr)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.acousticbrainzTags_groupBox)

        self.retranslateUi(AcousticbrainzOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(AcousticbrainzOptionsPage)

    def retranslateUi(self, AcousticbrainzOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        self.acousticbrainzTags_groupBox.setTitle(_translate("AcousticbrainzOptionsPage", "Acousticbrainz Tags"))
        self.add_simplemood.setText(_translate("AcousticbrainzOptionsPage", "Add simple Mood tags"))
        self.add_simplegenre.setText(_translate("AcousticbrainzOptionsPage", "Add simple Genre tags"))
        self.add_keybpm.setText(_translate("AcousticbrainzOptionsPage", "Add simple BPM and Key tags"))
        self.add_fullhighlevel.setText(_translate("AcousticbrainzOptionsPage", "Add all highlevel Acousticbrainz tags"))
        self.add_sublowlevel.setText(_translate("AcousticbrainzOptionsPage", "Add a subset of the lowlevel Acousticbrainz tags"))
        self.sublowlevel_descr.setText(_translate("AcousticbrainzOptionsPage", "<html><head/><body><p>The low level subset include:</p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">rhythm:bpm</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">tonal:chords_change_rate</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">tonal:chords_key</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">tonal:chords_scale</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">tonal:key_key</li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">tonal:key_scale</li></ul></body></html>"))
