# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_options_remove_soundtrack.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemoveSoundtrackOptionsPage(object):
    def setupUi(self, RemoveSoundtrackOptionsPage):
        RemoveSoundtrackOptionsPage.setObjectName("RemoveSoundtrackOptionsPage")
        RemoveSoundtrackOptionsPage.resize(600, 500)
        self.vboxlayout = QtWidgets.QVBoxLayout(RemoveSoundtrackOptionsPage)
        self.vboxlayout.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.regex_group = QtWidgets.QGroupBox(RemoveSoundtrackOptionsPage)
        self.regex_group.setObjectName("regex_group")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.regex_group)
        self.vboxlayout1.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout1.setSpacing(2)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.regex_label = QtWidgets.QLabel(self.regex_group)
        font = QtGui.QFont()
        font.setBold(True)
        self.regex_label.setFont(font)
        self.regex_label.setObjectName("regex_label")
        self.vboxlayout1.addWidget(self.regex_label)
        self.regex_hint = QtWidgets.QLabel(self.regex_group)
        self.regex_hint.setOpenExternalLinks(True)
        self.regex_hint.setObjectName("regex_hint")
        self.vboxlayout1.addWidget(self.regex_hint)
        self.regex_pattern = QtWidgets.QPlainTextEdit(self.regex_group)
        self.regex_pattern.setObjectName("regex_pattern")
        self.vboxlayout1.addWidget(self.regex_pattern)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.button_layout.addItem(spacerItem)
        self.reset_button = QtWidgets.QPushButton(self.regex_group)
        self.reset_button.setObjectName("reset_button")
        self.button_layout.addWidget(self.reset_button)
        self.vboxlayout1.addLayout(self.button_layout)
        self.vboxlayout.addWidget(self.regex_group)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem1)

        self.retranslateUi(RemoveSoundtrackOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(RemoveSoundtrackOptionsPage)

    def retranslateUi(self, RemoveSoundtrackOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        self.regex_group.setTitle(_translate("RemoveSoundtrackOptionsPage", "Remove Soundtrack Settings"))
        self.regex_label.setText(_translate("RemoveSoundtrackOptionsPage", "Regex pattern to remove soundtrack information:"))
        self.regex_hint.setText(_translate("RemoveSoundtrackOptionsPage", "<html><head/><body><p>Use <a href=\"https://regex101.com/\"><span style=\" text-decoration: underline; color:#1f9b5d;\">regex101.com</span></a> to test your pattern!</p></body></html>"))
        self.reset_button.setText(_translate("RemoveSoundtrackOptionsPage", "Reset to Default"))
